### ISSUE TITLE
How to reduce System RAM? 

### ISSUE THREAD

**Issue by pendekarcode** [ayush-thakur02/stable-diffusion-xl#1]
I'm using Free Colab version (Tesla T4). When running some prompts. Then generate 2 - 3 images. my system RAM increased to 12 GB

**Comment by ayush-thakur02** [comment]
The image generation process currently consumes a significant amount of RAM for each individual image. Since you are using the free Colab version, generating images should still be feasible, with each image taking approximately 6 to 8 seconds to generate.

If you encounter any memory-related errors, you can address them by adding the following code at the beginning:

```python
!curl -Lo memfix.zip https://github.com/nolanaatama/microsoftexcel/raw/main/memfix.zip
!unzip /content/memfix.zip
!apt -y update -qq
%env LD_PRELOAD=/content/libtcmalloc_minimal.so.4
```

Furthermore, I plan to update the code to optimize memory usage. It's important to note that this optimized version may still require around 10 to 12 GB of RAM, and since you have 15 GB available, you should not encounter any issues.
